source 'https://github.com/Workable/PodSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ErrorHandler_Example' do

  pod 'ErrorHandler', :path => "../"
  pod 'ErrorHandler/Alamofire', :path => "../"

  target 'ErrorHandler_Tests' do
    inherit! :search_paths
  end
end
